server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: "postgres"
    password: "1234"
    driver-class-name: org.postgresql.Driver

#  datasource:
#    url: jdbc:mysql://localhost:3306/introSpringDb
#    username: "root"
#    password: ""
#    driver-class-name: com.mysql.jdbc.Driver

#  datasource:
#    url: jdbc:h2:mem:demoBF2022
#    username: sa
#    password: "1234"
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

